import: [rgnn_encoder, lookup_embedder]

job.type: train
dataset.name: fb15k-237
model: ragat

ragat:
  entity_embedder:
    type: lookup_embedder
    initialize: xavier_normal_ 
    regularize: ''
    dim: 100
    +++: +++
  relation_embedder:
    type: lookup_embedder
    initialize: xavier_normal_
    regularize: ''
    dim: 100
    +++: +++
  encoder:
    type: rgnn_encoder
    num_layers: 1
    activation: relu
    weight_init: xavier_normal_
    edge_dropout: 0.0 
    self_edge_dropout: 0.0 
    emb_entity_dropout: 0.3  
    rel_transformation: linear 
    message_passing_args:
      propagation: direction  
      composition: cross_weighted 
      edge_norm: False 
      emb_propagation_dropout: 0.4 
      attention: True
      num_heads: 2
      message_weight: True
    +++: +++
  decoder: 
    model: distmult
    type: distmult
    scorer: DistMultScorer

train:
  type: KvsAll
  loss: bce
  max_epochs: 1500
  batch_size: 1024
  optimizer.default:
    type: Adam
    args:
      amsgrad: False
      eps: 1e-08
      lr: 0.001
      weight_decay: 0.0

KvsAll:
  label_smoothing: 0.1

valid:
  early_stopping: 
    patience: 30 


random_seed:
  numpy: 41504
  torch: 41504
