# Default settings in W-GCN for FB15k.237
import: [rgnn_encoder, lookup_embedder]

job.type: train
dataset.name: fb15k-237
model: wgcn

wgcn:
  entity_embedder:
    type: lookup_embedder
    initialize: xavier_normal_
    regularize: ''
    dim: 200
    +++: +++
  relation_embedder:
    type: lookup_embedder
    initialize: xavier_normal_
    regularize: ''
    dim: 200
    +++: +++
  encoder:
    type: rgnn_encoder
    layer_type: weighted_gcn 
    #layer_type: message_passing
    activation: tanh
    rel_transformation: self
    num_layers: 2
    emb_entity_dropout: 0.25  
    bias: True 
  decoder: # here ConvE, WGCN uses an adapted version of ConvE (TransConvE)
    model: reciprocal_relations_model
    type: reciprocal_relations_model
    base_model.type: conve
      #type: kge_model
    reciprocal_relations_model.base_model.type: conve
    base_model:
      round_dim: True
      feature_map_dropout: 0.25
      projection_dropout: 0.25
      entity_embedder: # see as output size of Rgnn
        dim: 200            
        +++: +++
      relation_embedder:
        dim: 200            
        +++: +++
    scorer: ConvEScorer 

train:
  type: KvsAll
  loss: bce
  max_epochs: 1000
  batch_size: 128
  optimizer.default:
    type: Adam
    args:
      amsgrad: False
      eps: 1e-08
      lr: 0.003
      weight_decay: 1.0

KvsAll:
  label_smoothing: 0.1

random_seed:
  numpy: 41504
  torch: 41504
