# Default settings from rgcn PyTorch implementation TODO cite 
import: [rgnn_encoder, lookup_embedder]

job.type: train
dataset.name: fb15k-237
model: rgcn

rgcn:
  entity_embedder:
    type: lookup_embedder
    dim: 500
    initialize: xavier_uniform_
    regularize: 'lp'
    +++: +++

  relation_embedder:
    type: lookup_embedder
    dim: 500
    initialize: xavier_uniform_
    regularize: 'lp'
    +++: +++

  encoder:
    type: rgnn_encoder
    num_layers: 1
    layer_type: torch_rgcn
    bias: True 
    weight_init: xavier_uniform_
    weight_decomposition: block # other option: basis
    num_blocks_or_bases: 100
    rel_transformation: self 
    edge_dropout: 0.4
    self_edge_dropout: 0.2
    +++: +++  
  
  decoder:
    model: distmult
    type: distmult
    scorer: DistMultScorer 

train:
  type: negative_sampling
  loss: bce
  #max_epochs: 12000
  max_epochs: 1
  batch_size: 512
  optimizer.default:
    type: Adam
    args:
      amsgrad: False
      # betas: (0.9, 0.999)
      # eps: 1e-08
      lr: 0.01
      weight_decay: 0.0

negative_sampling:
  graph_sampling: edge_neighbourhood
  graph_sampling_size: 30000
  num_samples:
    s: 10
    p: 10
    o: -1  # means: as s
  filtering:
    s: True
    o: True
    p: True
    implementation: fast_if_available
  

valid:
  early_stopping: 
    patience: 50 

random_seed:
  numpy: 41504
  torch: 41504
