# Get all settings similar to default settings in SACN
import: [rgnn_encoder, lookup_embedder]

job.type: train
dataset.name: wnrr
model: wgcn

wgcn:
  entity_embedder:
    type: lookup_embedder
    initialize: xavier_normal_
    regularize: ''
    dim: 200
    +++: +++
  relation_embedder:
    type: lookup_embedder
    initialize: xavier_normal_
    regularize: ''
    dim: 200
    +++: +++
  encoder:
    type: rgnn_encoder
    layer_type: weighted_gcn 
    activation: tanh
    rel_transformation: self
    num_layers: 2
    #1_out_dim: 200
    #2_out_dim: 200
    emb_entity_dropout: 0.25  # used on the entity output of the rgnn layer
    self_edge_dropout: 0.0
    edge_dropout: 0.0
    bias: True 
    weight_decomposition: None 
    num_blocks_or_bases: -1
  decoder: # here normal ConvE, SACN uses an adapted version of ConvE
    model: reciprocal_relations_model
    type: reciprocal_relations_model
    base_model.type: conve
      #type: kge_model
    reciprocal_relations_model.base_model.type: conve
    base_model:
      round_dim: True
      entity_embedder: # see as output size of Rgnn
        dim: 200            
        +++: +++
      relation_embedder:
        dim: 200            
        +++: +++
    scorer: ConvEScorer 

train:
  type: KvsAll
  loss: bce
  max_epochs: 1000
  batch_size: 128
  optimizer.default:
    type: Adam
    args:
      amsgrad: False
      # betas: (0.9, 0.999)
      eps: 1e-08
      lr: 0.003
      weight_decay: 1.0

KvsAll:
  label_smoothing: 0.1

valid:
  early_stopping: 
    patience: 0 #especially for RGCN!


random_seed:
  numpy: 41504
  torch: 41504
