# Default Settings for RAGAT on WN18RR
import: [rgnn_encoder, lookup_embedder]

job.type: train
dataset.name: wnrr
model: ragat

ragat:
  entity_embedder:
    type: lookup_embedder
    initialize: xavier_normal_ 
    regularize: ''
    dim: 100
    +++: +++
  relation_embedder:
    type: lookup_embedder
    initialize: xavier_normal_
    regularize: ''
    dim: 100
    +++: +++
  encoder:
    type: rgnn_encoder
    num_layers: 1
    activation: relu
    weight_init: xavier_normal_
    bias: False 
    bias_init: zeros_ 
    emb_entity_dropout: 0.3  
    rel_transformation: linear 
    layer_type: message_passing 
    # Specific Arguments for the MessagePassingLayer
    message_passing_args:
      propagation: direction  #
      composition: cross_weighted 
      edge_norm: False 
      emb_propagation_dropout: 0.4 
      attention: True
      num_heads: 1
      message_weight: True
    +++: +++
  decoder: # here normal ConvE, RAGAT uses InteractE
    model: reciprocal_relations_model
    type: reciprocal_relations_model
    base_model.type: conve
      #type: kge_model
    reciprocal_relations_model.base_model.type: conve
    base_model:
      round_dim: True
      entity_embedder: # see as output size of Rgnn
        dim: 200            
        +++: +++
      relation_embedder:
        dim: 200            
        +++: +++
    scorer: ConvEScorer 

train:
  type: KvsAll
  loss: bce
  max_epochs: 1500
  batch_size: 256
  optimizer.default:
    type: Adam
    args:
      amsgrad: False
      eps: 1e-08
      lr: 0.001
      weight_decay: 0.0

KvsAll:
  label_smoothing: 0.1

random_seed:
  numpy: 41504
  torch: 41504
