# Time measurement settings for CompGCN
import: [rgnn_encoder, lookup_embedder]

job.type: train
dataset.name: fb15k-237
model: compgcn

compgcn:
  entity_embedder:
    type: lookup_embedder
    initialize: xavier_normal_
    regularize: ''
    dim: 100
    +++: +++
  relation_embedder:
    type: lookup_embedder
    initialize: xavier_normal_
    regularize: ''
    dim: 100
    +++: +++
  encoder:
    type: rgnn_encoder
    # CompGCN specific RGNN parameters:
    layer_type: message_passing 
    message_passing_args:
      edge_norm: True
      emb_propagation_dropout: 0.3  
      propagation: direction 
      composition: ccorr # sub, mult and ccorr in original implementation
      message_weight: False
      attention: False
    activation: tanh
    rel_transformation: linear
    num_layers: 1
    emb_entity_dropout: 0.1  
    bias: False 
  decoder:
    model: transe
    type: transe
    scorer: TransEScorer 

train:
  type: negative_sampling
  loss: bce
  max_epochs: 1
  batch_size: 256
  optimizer.default:
    type: Adam
    args:
      amsgrad: False
      lr: 0.01
      weight_decay: 0.0

negative_sampling:
  num_samples:
    s: 10
    p: 10
    o: -1  
  filtering:
    s: True
    o: True
    p: True
    implementation: fast_if_available

random_seed:
  numpy: 41504
  torch: 41504
