# Time measurement settings for RAGAT
import: [rgnn_encoder, lookup_embedder]

job.type: train
dataset.name: fb15k-237
model: ragat

ragat:
  entity_embedder:
    type: lookup_embedder
    initialize: xavier_normal_ 
    regularize: ''
    dim: 100
    +++: +++
  relation_embedder:
    type: lookup_embedder
    initialize: xavier_normal_
    regularize: ''
    dim: 100
    +++: +++
  encoder:
    type: rgnn_encoder
    num_layers: 1
    activation: relu
    weight_init: xavier_normal_
    bias: False 
    bias_init: zeros_ 
    emb_entity_dropout: 0.3  
    rel_transformation: linear 
    layer_type: message_passing 
    # Specific Arguments for the MessagePassingLayer
    message_passing_args:
      propagation: direction  
      composition: cross_weighted 
      edge_norm: False 
      emb_propagation_dropout: 0.4 
      attention: True
      num_heads: 2
      message_weight: True
    +++: +++
  decoder:
    model: transe
    type: transe
    scorer: TransEScorer 

train:
  type: negative_sampling
  loss: bce
  max_epochs: 1
  batch_size: 256 
  optimizer.default:
    type: Adam
    args:
      amsgrad: False
      lr: 0.01
      weight_decay: 0.0

negative_sampling:
  num_samples:
    s: 10
    p: 10
    o: -1  # means: as s
  filtering:
    s: True
    o: True
    p: True
    implementation: fast_if_available

random_seed:
  numpy: 41504
  torch: 41504

