# Get all settings similar to default settings in CompGCN
import: [rgnn_encoder, lookup_embedder]

job.type: train
dataset.name: toy
model: ragat
#model: transe

#rgcn:
ragat:
  entity_embedder:
    type: lookup_embedder
    dim: 100
    +++: +++

  relation_embedder:
    type: lookup_embedder
    dim: 100
    +++: +++

  encoder:
    type: rgnn_encoder
    num_layers: 1
    # 1_out_dim: 200
    +++: +++  

train:
  type: negative_sampling
  loss: bce
  max_epochs: 200
  batch_size: 1024
  optimizer.default:
    type: Adam
    args:
      amsgrad: False
      # betas: (0.9, 0.999)
      eps: 1e-08
      lr: 0.001
      weight_decay: 0.0

negative_sampling:
# to reproduce graph sampling from torch-rgcn set batch_size=graph_sampling_size
  graph_sampling: edge_neighbourhood
  graph_sampling_size: 1600

valid:
  early_stopping: 
    patience: 0 #especially for RGCN!


random_seed:
  numpy: 41504
  torch: 41504
